services:
  db:
    #image: mysql:8.0.27
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    volumes: ['db_data:/var/lib/mysql']
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    networks:
      - wpsite
    build:
        context: .
        dockerfile: Dockerfile
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - wpsite
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes: 
      - 'wp_data:/var/www/html'
      - './wp-content:/var/www/html/wp-content'
    ports:
      - 8008:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
  wp_data: